[pytest]
pythonpath = .
markers =
    smoke: marks tests related to smoke test
    login: marks tests related to user login
    positive: marks tests related to positive test
    negative: marks tests related to negative test
    only: marks tests related to only test